### ISSUE TITLE
Question about the coverage calculation.

### ISSUE THREAD

**Issue by Musketeer-D** [PengNi/plant_5mC_analysis#2]
Dear Ni,
  Can you tell me how do you calculate the 'coverage' mentioned in your paper https://doi.org/10.1101/2021.02.07.430077? 
  As you mentioned in #1 , 'at least 20x coverage of reads are needed to get a stable result', do you mean the total read (including fail reads of guppy) or just pass read of guppy should be at least 20x coverage ?

**Comment by PengNi** [comment]
@musketeerD , thanks for your interest of our tool. We only count reads in PASS directory after basecalling using Guppy. We use samtools to estimate depth of the reads aligned to the reference genome.

**Comment by Musketeer-D** [comment]
Thank you for your kind help! 
So,'at least 20x coverage of reads are needed to get a stable result' means I need to have at least 20x mapped pass reads ?

**Comment by PengNi** [comment]
Yes.

**Comment by Musketeer-D** [comment]
Thanks so much again!
